### ISSUE TITLE
Add more items to gitignore

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-cms-installer#12]
Right now we just gitignore the basics relevant to this installer but there are a few more items that will make life easier for devs:

- node_modules
- vendor
- chassis / chassis-<project-name>
- ...

@rmccue @pdewouters does that cover it or shall we add some defaults for IDEs and things like `.vscode`, `.idea` etc?

**Comment by rmccue** [comment]
IMO, we should let the teams add their own entries to the gitignore for anything we're not supplying. I'd include `node_modules` in that, as we don't add any of those.

Also, while we're changing this, we should add a comment to the file to note they're part of Altis.

**Comment by pdewouters** [comment]
I think it's a good thing for developer experience if we include some examples of common ignored patterns.
