### ISSUE TITLE
Exclude Uploads directory from Git

### ISSUE THREAD

**Issue by fklein-lu** [humanmade/altis-cms-installer#19]
The installer should add a default entry to `.gitignore` to exclude `/content/uploads` from being tracked in version control.

**Comment by roborourke** [comment]
Cheers @fklein-lu, will be in v2

**Comment by roborourke** [comment]
@fklein-lu we track `~0.2.1` in humanmade/altis-cms so a `composer update` should get you the latest version, not that it'll help you now! Thanks for the bug report 👍
